### ISSUE TITLE
about how to use the train result to predict new svg file

### ISSUE THREAD

**Issue by tornado96** [microsoft/YOLaT-VectorGraphicsRecognition#4]
Dr.Jiang,
Sorry to bother you.I am a novice and I am not very familiar with how to use the trained model for new predictions. Could you please explain to me how to do that? I have followed the operation steps on Git to train the model and obtained the file "run182_2_best.pth". So, how can I use this training result to predict new files? Thank you.

**Comment by 1TTT9** [comment]
I thought you can simply use script detect.py to do that stuff with extra argument "pretrained_model". It works on my case.

**Comment by tornado96** [comment]
tks
